import { Poppins  } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const poppins = Poppins({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export const metadata = {
  title: "Majhi Navi Mumbai",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex flex-col min-h-screen justify-between`}
      >
         <nav className="w-full bg-white shadow-md py-4 px-6 flex items-center justify-center md:justify-between">
        <Image src="/logo.png" alt="logo" height={100} width={240} />
      </nav>
        {children}

        <footer className="text-white text-center">
          <marquee className="bg-green-800 text-white text-xl py-1" behavior="" direction="">
            Subscribe now for  1  year and get service for 1.5 year.  
          </marquee>
          <div className="bg-gray-900 py-4">
        <p className="text-lg">Contact: +91 91524 18196</p>
        <p className="text-sm">© {new Date().getFullYear()} Majhi Navi Mumbai. All Rights Reserved.</p>
          </div>
      </footer>
      </body>
    </html>
  );
}
